"""Sync the canonical Berg Agents theme into ``docs/styles/``.

Run from the project root:

    python -m berg_agents.ui.theme.sync          # write docs/styles/
    python -m berg_agents.ui.theme.sync --check # exit 1 if drift

The script generates ``docs/styles/custom.css`` and
``docs/styles/extra.css`` from the canonical sources so the docs site
and the webapp stay aligned.

This is intentionally a *generator* (no symlinks) so the docs site keeps
working when ``docs/`` is published as a static export without the rest
of the repository.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_THEME_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _THEME_DIR.parents[3]
_DOCS_STYLES = _REPO_ROOT / "docs" / "styles"


def _read(rel: str) -> str:
    return (_THEME_DIR / rel).read_text(encoding="utf-8")


def _build_custom_css() -> str:
    """Assemble docs/styles/custom.css from the canonical token + component files."""
    header = (
        "/* Custom CSS Styles for Semantic Research Dashboard Documentation */\n"
        "/*-- scss:defaults --*/\n"
        "@defaults;\n"
        "/*\n"
        " * AUTO-GENERATED by berg_agents.ui.theme.sync — edit the canonical\n"
        " * sources in berg_agents/ui/theme/ instead of this file.\n"
        " */\n\n"
    )
    body = (
        _read("tokens/colors.css")
        + "\n"
        + _read("tokens/typography.css")
        + "\n"
        + _read("tokens/spacing.css")
        + "\n"
        + _read("components/base.css")
        + "\n"
        + _read("components/banner.css")
        + "\n"
        + _read("presets/light.css")
    )
    return header + body


def _build_extra_css() -> str:
    """Assemble docs/styles/extra.css — additional Quarto-specific tweaks.

    Kept as a separate file so the generated layer above stays self-contained.
    """
    return (
        "/* Custom CSS Styles for SofiaBillBerg's Documentation */\n"
        "/* AUTO-GENERATED — edit in berg_agents/ui/theme/ instead. */\n"
        "/* Main theme coloring */\n"
        ".background-color { background-color: #3b528b; }\n"
        "/* Title banner */\n"
        ".quarto-title-banner { background: var(--berg-gradient-brand); color: white; padding: 2rem 2px; }\n"
        ".quarto-title-banner .title { color: white; font-weight: 700; text-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); font-size: 2.5em; margin-bottom: 1rem; }\n"
        ".quarto-title-banner .subtitle { color: rgba(255, 255, 255, 0.9); font-size: 1.2em; font-weight: 300; }\n"
    )


def sync() -> bool:
    """Write generated CSS into docs/styles/. Returns True on success."""
    if not _DOCS_STYLES.exists():
        print(
            f"[theme.sync] docs/styles/ not found at {_DOCS_STYLES} — skipping",
            file=sys.stderr,
        )
        return True
    (_DOCS_STYLES / "custom.css").write_text(
        _build_custom_css(), encoding="utf-8"
    )
    (_DOCS_STYLES / "extra.css").write_text(
        _build_extra_css(), encoding="utf-8"
    )
    print(f"[theme.sync] wrote {_DOCS_STYLES / 'custom.css'}")
    print(f"[theme.sync] wrote {_DOCS_STYLES / 'extra.css'}")
    return True


def check() -> bool:
    """Return True if docs/styles/ is in sync (or absent)."""
    if not _DOCS_STYLES.exists():
        return True
    expected_custom = _build_custom_css()
    expected_extra = _build_extra_css()
    actual_custom = (_DOCS_STYLES / "custom.css").read_text(encoding="utf-8")
    actual_extra = (_DOCS_STYLES / "extra.css").read_text(encoding="utf-8")
    if expected_custom != actual_custom:
        print(
            "[theme.sync] drift in docs/styles/custom.css — run `python -m berg_agents.ui.theme.sync`",
            file=sys.stderr,
        )
        return False
    if expected_extra != actual_extra:
        print(
            "[theme.sync] drift in docs/styles/extra.css — run `python -m berg_agents.ui.theme.sync`",
            file=sys.stderr,
        )
        return False
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync Berg Agents theme to docs/styles/"
    )
    parser.add_argument(
        "--check", action="store_true", help="Exit non-zero if drift detected"
    )
    args = parser.parse_args(argv)
    if args.check:
        return 0 if check() else 1
    sync()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
