- id: ruff-check
  name: ruff check
  description: "Run 'ruff check' for extremely fast Python linting"
  entry: ruff check --force-exclude
  language: python
  types_or: [ python, pyi, jupyter ]
  args: [ ]
  require_serial: true
  additional_dependencies: [ ]
  minimum_pre_commit_version: "2.9.2"

- id: ruff-format
  name: ruff format
  description: "Run 'ruff format' for extremely fast Python formatting"
  entry: ruff format --force-exclude
  language: python
  types_or: [ python, pyi, jupyter ]
  args: [ ]
  require_serial: true
  additional_dependencies: [ ]
  minimum_pre_commit_version: "2.9.2"

# Legacy alias
- id: ruff
  name: ruff (legacy alias)
  description: "Run 'ruff check' for extremely fast Python linting"
  entry: ruff check --force-exclude
  language: python
  types_or: [ python, pyi, jupyter ]
  args: [ ]
  require_serial: true
  additional_dependencies: [ ]
  minimum_pre_commit_version: "2.9.2"
- id: check-illegal-windows-names
  name: check illegal windows names
  entry: Illegal Windows filenames detected
  language: fail
  files: '(?i)((^|/)(CON|PRN|AUX|NUL|COM[\d¹²³]|LPT[\d¹²³])(\.|/|$)|[<>:\"\\|?*\x00-\x1F]|/[^/]*[\.\s]/|[^/]*[\.\s]$)'
- id: check-json
  name: check json
  description: checks json files for parseable syntax.
  entry: check-json
  language: python
  types: [ json ]
- id: pretty-format-json
  name: pretty format json
  description: sets a standard for formatting json files.
  entry: pretty-format-json
  language: python
  types: [ json ]
- id: destroyed-symlinks
  name: detect destroyed symlinks
  description: detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
  entry: destroyed-symlinks
  language: python
  types: [ file ]
  stages: [ pre-commit, pre-push, manual ]
- id: detect-aws-credentials
  name: detect aws credentials
  description: detects *your* aws credentials from the aws cli credentials file.
  entry: detect-aws-credentials
  language: python
  types: [ text ]
- id: detect-private-key
  name: detect private key
  description: detects the presence of private keys.
  entry: detect-private-key
  language: python
  types: [ text ]
- id: sort-simple-yaml
  name: sort simple yaml files
  description: sorts simple yaml files which consist only of top-level keys, preserving comments and blocks.
  language: python
  entry: sort-simple-yaml
  files: '^$'
- id: trailing-whitespace
  name: trim trailing whitespace
  description: trims trailing whitespace.
  entry: trailing-whitespace-fixer
  language: python
  types: [ text ]
  stages: [ pre-commit, pre-push, manual ]
  minimum_pre_commit_version: 3.2.0
