
- id: check-added-large-files
  name: check for added large files
  description: prevents giant files from being committed.
  entry: check-added-large-files
  language: python
  stages: [pre-commit, pre-push, manual]
  minimum_pre_commit_version: 3.2.0
- id: check-ast
  name: check python ast
  description: simply checks whether the files parse as valid python.
  entry: check-ast
  language: python
  types: [python]
- id: check-builtin-literals
  name: check builtin type constructor use
  description: requires literal syntax when initializing empty or zero python builtin types.
  entry: check-builtin-literals
  language: python
  types: [python]
- id: check-case-conflict
  name: check for case conflicts
  description: checks for files that would conflict in case-insensitive filesystems.
  entry: check-case-conflict
  language: python
- id: check-executables-have-shebangs
  name: check that executables have shebangs
  description: ensures that (non-binary) executables have a shebang.
  entry: check-executables-have-shebangs
  language: python
  types: [text, executable]
  stages: [pre-commit, pre-push, manual]
  minimum_pre_commit_version: 3.2.0
- id: check-illegal-windows-names
  name: check illegal windows names
  entry: Illegal Windows filenames detected
  language: fail
  files: '(?i)((^|/)(CON|PRN|AUX|NUL|COM[\d¹²³]|LPT[\d¹²³])(\.|/|$)|[<>:\"\\|?*\x00-\x1F]|/[^/]*[\.\s]/|[^/]*[\.\s]$)'
- id: check-json
  name: check json
  description: checks json files for parseable syntax.
  entry: check-json
  language: python
  types: [json]
- id: check-shebang-scripts-are-executable
  name: check that scripts with shebangs are executable
  description: ensures that (non-binary) files with a shebang are executable.
  entry: check-shebang-scripts-are-executable
  language: python
  types: [text]
  stages: [pre-commit, pre-push, manual]
  minimum_pre_commit_version: 3.2.0
- id: check-merge-conflict
  name: check for merge conflicts
  description: checks for files that contain merge conflict strings.
  entry: check-merge-conflict
  language: python
  types: [text]
- id: check-symlinks
  name: check for broken symlinks
  description: checks for symlinks which do not point to anything.
  entry: check-symlinks
  language: python
  types: [symlink]
- id: check-toml
  name: check toml
  description: checks toml files for parseable syntax.
  entry: check-toml
  language: python
  types: [toml]
- id: check-vcs-permalinks
  name: check vcs permalinks
  description: ensures that links to vcs websites are permalinks.
  entry: check-vcs-permalinks
  language: python
  types: [text]
- id: check-xml
  name: check xml
  description: checks xml files for parseable syntax.
  entry: check-xml
  language: python
  types: [xml]
- id: check-yaml
  name: check yaml
  description: checks yaml files for parseable syntax.
  entry: check-yaml
  language: python
  types: [yaml]
- id: debug-statements
  name: debug statements (python)
  description: checks for debugger imports and py37+ `breakpoint()` calls in python source.
  entry: debug-statement-hook
  language: python
  types: [python]
- id: destroyed-symlinks
  name: detect destroyed symlinks
  description: detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
  entry: destroyed-symlinks
  language: python
  types: [file]
  stages: [pre-commit, pre-push, manual]
- id: detect-private-key
  name: detect private key
  description: detects the presence of private keys.
  entry: detect-private-key
  language: python
  types: [text]
- id: fix-byte-order-marker
  name: fix utf-8 byte order marker
  description: removes utf-8 byte order marker.
  entry: fix-byte-order-marker
  language: python
  types: [text]
# pyupgrade https://github.com/asottile/pyupgrade

- id: mixed-line-ending
  name: mixed line ending
  description: replaces or checks mixed line ending.
  entry: mixed-line-ending
  language: python
  types: [text]
  stages: [pre-commit, pre-push, manual]

- id: no-commit-to-branch
  name: "don't commit to branch"
  entry: no-commit-to-branch
  language: python
  pass_filenames: false
  always_run: true
- id: sort-simple-yaml
  name: sort simple yaml files
  description: sorts simple yaml files which consist only of top-level keys, preserving comments and blocks.
  language: python
  entry: sort-simple-yaml
  files: '^$'

- id: run-autofix
  name: run-autofix
  entry: project_management/run_autofix.sh
  language: script
  stages: [pre-commit, manual]

- id: run-vis
  name: run-vis
  entry: project_management/run_vis.sh
  language: script
  stages: [pre-push, manual]
- id: run-formatters
  name: run-formatters
  entry: project_management/run_formatters.sh
  language: script
  stages: [pre-push, manual]
- id: run-analyzers
  name: run-analyzers
  entry: project_management/run_analyzers.sh
  language: script
  stages: [pre-push, manual]
