[pydoctor]
project-name = Berg Agents
add-package =
    berg_agents
docformat = restructuredtext
verbose = 1
use-hardlinks = true
warnings-as-errors = false
intersphinx =
    https://docs.python.org/3/objects.inv
    https://python.org
    https://docs.twisted.org/en/stable/api/objects.inv
    https://github.io
    https://readthedocs.io
    https://sbert.net
    https://numpy.org/doc/stable/objects.inv
    https://docs.pydantic.dev/latest/objects.inv
    https://reference.langchain.com/python/langchain-core/objects.inv
    https://reference.langchain.com/python/langchain/objects.inv
    https://reference.langchain.com/python/langgraph/objects.inv
    https://langchain.com
    https://github.io
intersphinx-file = apidocs/objects.inv :: https://github.com/SofiaBillBerg/code_agent/blob/main/docs/objects.inv
# intersphinx-file =/tmp/project/docs/objects.inv :: https://protected.docs/project/api
html-output = apidocs
process-types = true
