[pydoctor]
project-name = Code_agent
add-package =
    code_agent
docformat = restructuredtext
verbose = 1
warnings-as-errors = true
intersphinx =
    https://docs.python.org/3/objects.inv
    https://python.org
    https://docs.twisted.org/en/stable/api/objects.inv
    https://github.io
    https://readthedocs.io
    https://sbert.net
    https://numpy.org/doc/stable/objects.inv
# intersphinx-file = apidocs/objects.inv
# intersphinx-file =/tmp/project/docs/objects.inv :: https://protected.docs/project/api
html-output = apidocs
process-types  = true
