"""Property and example tests for Settings extensions.

Tests for the checkpoint_dir, stream_enabled, and provider_list fields
added to the Settings class, plus validation behavior.
"""

from __future__ import annotations

import logging
import pathlib

from code_agent.config.settings import (
    _ENV_UNSET,
    Settings,
    _expand_env_vars,
    _load_substitution_env,
    get_settings,
)
import hypothesis
from hypothesis import given, settings
from hypothesis import strategies as st
import pytest

# Tag: Feature: agent-core-enhancement, Property 11: Settings checkpoint_dir validation never raises
# Tag: Feature: agent-core-enhancement, Property 12: Settings round-trip

@pytest.fixture(autouse=True)
def reset_settings_cache():
    """Clear the Settings cache before each test to ensure fresh instances."""
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


def _make_provider_dict() -> st.SearchStrategy[dict[str, str]]:
    """Generate a valid provider dict with name and model keys."""
    return st.fixed_dictionaries({
        "name": st.text(min_size=1, max_size=50),
        "model": st.text(min_size=1, max_size=50),
    })


class TestSettingsExtensions:
    """Tests for extended Settings fields and validation."""

    # Tag: Feature: agent-core-enhancement, Property 11: Settings checkpoint_dir validation never raises
    @given(
        checkpoint_dir=st
        .text(min_size=3, max_size=200)
        .filter(lambda x: not any(c in x for c in ["\x00", "\n", "\r"]))
        .filter(lambda x: not x.startswith("~")),  # Skip tilde paths
    )
    @settings(
        max_examples=50,
        suppress_health_check=[hypothesis.HealthCheck.function_scoped_fixture],
    )
    def test_checkpoint_dir_validation_never_raises(
        self,
        checkpoint_dir: str,
        caplog: pytest.LogCaptureFixture,
        tmp_path: pathlib.Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """Property 11: Settings checkpoint_dir validation never raises.

        The _validate_checkpoint_dir validator logs a WARNING (never raises)
        for any path - even invalid or inaccessible ones.

        The test runs inside a temporary directory so that any relative
        checkpoint_dir values generated by Hypothesis resolve against
        tmp_path instead of the repository's tests/ directory (which
        previously caused garbage-named directories to be created in tests/).

        :param checkpoint_dir: Random checkpoint directory path
        :param caplog: Pytest log capture fixture
        :param tmp_path: Pytest temporary directory fixture
        :param monkeypatch: Pytest monkeypatch fixture
        """
        monkeypatch.chdir(tmp_path)

        with caplog.at_level(logging.WARNING):
            settings = Settings(checkpoint_dir=checkpoint_dir)

        assert settings is not None
        assert isinstance(settings.checkpoint_dir, str)

    # Tag: Feature: agent-core-enhancement, Property 12: Settings round-trip
    @given(
        stream_enabled=st.one_of(st.just(True), st.just(False)),
        provider_list=st.one_of(
            st.just(None),
            st.lists(_make_provider_dict(), min_size=1, max_size=5),
        ),
    )
    @settings(
        max_examples=50,
        suppress_health_check=[hypothesis.HealthCheck.function_scoped_fixture],
    )
    def test_settings_round_trip(
        self, stream_enabled: bool, provider_list: list[dict[str, str]] | None
    ) -> None:
        """Property 12: Settings round-trip preserves field values.

        Creating a Settings instance and dumping it should preserve the
        stream_enabled and provider_list values.

        :param stream_enabled: Boolean for stream_enabled field
        :param provider_list: List of provider dicts or None
        """
        settings = Settings(
            stream_enabled=stream_enabled,
            provider_list=provider_list,
        )
        dumped = settings.model_dump()

        assert dumped["stream_enabled"] == stream_enabled
        assert dumped["provider_list"] == provider_list


class TestSettingsExampleTests:
    """Example tests for Settings extensions - concrete test cases."""

    def test_checkpoint_dir_default(self) -> None:
        """Example test: checkpoint_dir has the expected default value."""
        settings = Settings()

        assert settings.checkpoint_dir == "~/.code_agent/checkpoints/"

        settings2 = Settings(checkpoint_dir="/tmp/test_checkpoints")

        assert settings2.checkpoint_dir == "/tmp/test_checkpoints"

    def test_stream_enabled_default_false(self) -> None:
        """Example test: stream_enabled defaults to False (based on current implementation)."""
        settings = Settings()

        # Note: Based on current implementation, stream_enabled defaults to False
        # and stream=True is a separate boolean for general streaming behavior
        assert hasattr(settings, "stream_enabled")

        settings2 = Settings(stream_enabled=True)

        assert settings2.stream_enabled is True

    def test_provider_list_parses_json(self) -> None:
        """Example test: provider_list accepts JSON string and parses to dict."""
        parsed_list: list[dict[str, str]] = [
            {"name": "ollama", "model": "gpt-oss-20b"}
        ]
        settings = Settings(provider_list=parsed_list)

        assert settings.provider_list is not None
        assert len(settings.provider_list) == 1
        assert settings.provider_list[0]["name"] == "ollama"
        assert settings.provider_list[0]["model"] == "gpt-oss-20b"

        parsed_list2: list[dict[str, str]] = [
            {"name": "openai", "model": "gpt-4o"}
        ]
        settings2 = Settings(provider_list=parsed_list2)

        assert settings2.provider_list == parsed_list2

    def test_checkpoint_dir_expands_tilde(self) -> None:
        """Example test: checkpoint_dir preserves tilde in string form."""
        settings = Settings(checkpoint_dir="~/.code_agent/checkpoints")

        assert settings.checkpoint_dir.startswith("~")

    def test_stream_enabled_accepted_as_config(self) -> None:
        """Example test: stream_enabled can be set during initialization."""
        settings = Settings(stream_enabled=True)

        assert settings.stream_enabled is True


class TestEnvSubstitution:
    """Tests for ``${env:VAR}`` / ``${VAR}`` substitution in config files."""

    def test_exact_placeholder_expands(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A value that is exactly one placeholder expands to the env value."""
        monkeypatch.setenv("CODE_AGENT_SUBST_TEST", "secret-value")
        env = _load_substitution_env()

        assert (
            _expand_env_vars("${env:CODE_AGENT_SUBST_TEST}", env)
            == "secret-value"
        )
        assert (
            _expand_env_vars("${CODE_AGENT_SUBST_TEST}", env) == "secret-value"
        )

    def test_embedded_placeholder_expands(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Placeholders embedded in a larger string expand in place."""
        monkeypatch.setenv("CODE_AGENT_SUBST_TEST", "secret-value")
        env = _load_substitution_env()

        assert (
            _expand_env_vars("prefix-${CODE_AGENT_SUBST_TEST}-suffix", env)
            == "prefix-secret-value-suffix"
        )

    def test_unset_exact_placeholder_is_dropped(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """An exact placeholder for an unset var returns the drop sentinel."""
        monkeypatch.delenv("CODE_AGENT_SUBST_TEST", raising=False)
        env = _load_substitution_env()

        assert (
            _expand_env_vars("${env:CODE_AGENT_SUBST_TEST}", env) is _ENV_UNSET
        )

    def test_dict_drops_unset_keys(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Dict values referencing unset vars are dropped so defaults apply."""
        monkeypatch.setenv("CODE_AGENT_SUBST_SET", "value")
        monkeypatch.delenv("CODE_AGENT_SUBST_UNSET", raising=False)
        env = _load_substitution_env()

        result = _expand_env_vars(
            {
                "keep": "${env:CODE_AGENT_SUBST_SET}",
                "drop": "${env:CODE_AGENT_SUBST_UNSET}",
                "literal": "plain",
            },
            env,
        )

        assert result == {"keep": "value", "literal": "plain"}

    def test_list_drops_unset_items(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """List items referencing unset vars are dropped."""
        monkeypatch.setenv("CODE_AGENT_SUBST_SET", "value")
        monkeypatch.delenv("CODE_AGENT_SUBST_UNSET", raising=False)
        env = _load_substitution_env()

        result = _expand_env_vars(
            ["${env:CODE_AGENT_SUBST_SET}", "${env:CODE_AGENT_SUBST_UNSET}"],
            env,
        )

        assert result == ["value"]

    def test_non_string_values_passthrough(self) -> None:
        """Non-string nodes are returned unchanged."""
        env = _load_substitution_env()

        assert _expand_env_vars(42, env) == 42
        assert _expand_env_vars(None, env) is None
        assert _expand_env_vars(True, env) is True
