classDiagram

class EditFileTool {
    args_schema : type[BaseModel]
    description : str
    model_config
    name : str
    response_format : Literal['content_and_artifact']
    root : Path
    \_\_init\_\_(root_dir: str | Path)
    _arun(file_path: str, new_content: str, mode: str) tuple[str, FileObject]
    _backup_file(path: Path) str
    _edit_append(path: Path, content: str) None
    _edit_patch(path: Path, content: str) None
    _edit_replace(path: Path, content: str) None
    _run(file_path: str, new_content: str, mode: str) tuple[str, FileObject]
}
    style EditFileTool fill:[lavender
