classDiagram

class ReadFileTool {
    args_schema : type[BaseModel]
    description : str
    name : str
    root : Path
    \_\_init\_\_(root_dir: str | Path)
    _arun() str
    _run(file_path: str) str
}
    style ReadFileTool fill:[lavender
