classDiagram

class GeneralChatTool {
    args_schema : type[BaseModel]
    description : str
    llm
    name : str
    \_\_init\_\_(llm_instance: BaseChatModel)
    _arun() str
    _run(query: str) str
}
    style GeneralChatTool fill:[lavender
