classDiagram

class GenerateTestTool {
    args_schema : type[BaseModel]
    description : str
    model_config
    name : str
    response_format : Literal['content_and_artifact']
    root : Path
    \_\_init\_\_(root_dir: str | Path)
    _arun(file_path: str, tests_dir: str) tuple[str, FileObject]
    _run(file_path: str, tests_dir: str) tuple[str, FileObject]
}
    style GenerateTestTool fill:[lavender
